STUDY_NAME: "competencia-02-study-1-0"
BUCKETS: "/home/tomas_freilij/buckets"
BUCKET_ORIGIN: "b1"
BUCKET_TARGET: "b1"
DATASETS_PATH: "/home/tomas_freilij/datasets/"
SEMILLA: [50,100,150,400,700,1000,1500,2000,3000,4000,5000,10000,15000,20000,25000,30000,35000,40000,45000,50000,55000,60000,65000,70000]
MES_TRAIN: [202002, 202003, 202004, 202005, 202006, 202007, 202008, 202009, 202010, 202011, 202012, 202101]
MES_VALIDACION: 202102
MES_TEST: 202103
FINAL_TRAIN: [202003, 202004, 202005, 202006, 202007, 202008, 202009, 202010, 202011, 202012, 202101, 202102]
FINAL_PREDICT: 202104
GANANCIA_ACIERTO: 780000
COSTO_ESTIMULO: 20000
RUN_BAYESIAN_OPTIMIZATION: True
UNDERSAMPLING_FRACTION: 0.03
UNDERSAMPLED_DATASET: "competencia_02_undersampled_0_03.csv"
TRAIN_TEST_MODELS : True
