STUDY_NAME: "competencia-02-study-1-0"

BUCKET: "/home/tomas_freilij/buckets/b1"

DATASETS_PATH: "/home/tomas_freilij/datasets/"

DATASET_CRUDO_FILE: "competencia_02_crudo.csv.gz"
DATASET_TERNARIA_FILE: "competencia_02.csv"
DATASET_FE_FILE: "competencia_02_fe.csv"
DICCIONARIO_DATOS: "/home/tomas_freilij/dmeyf2025/competencia-02/diccionario_datos.csv"

MODELOS_PATH: "modelos/"

DATASET_FE_PATH: "competencia_02_fe.csv"
TABLE_NAME: "competencia_02_fe"
SEMILLA: [50,100,150,400,700,1000,1500,2000,3000,4000,5000]
MES_TRAIN: [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003, 202004, 202005, 202006, 202007, 202008, 202009, 202010, 202011, 202012, 202101, 202102]
MES_VALIDACION: 202104
MES_TEST: 202106
FINAL_TRAIN: [201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003, 202004, 202005, 202006, 202007, 202008, 202009, 202010, 202011, 202012, 202101, 202102, 202103, 202104, 202105, 202106]
FINAL_PREDICT: 202108
GANANCIA_ACIERTO: 780000
COSTO_ESTIMULO: 20000
RUN_BAYESIAN_OPTIMIZATION: True
UNDERSAMPLING_FRACTION: 0.7
