STUDY_NAME: "competencia-02-study-1-0"
BUCKETS: "/home/tomas_freilij/buckets"
BUCKET_ORIGIN: "b1"
BUCKET_TARGET: "b1"
SEMILLA: [50,100,150,400,700,1000,1500,2000,3000,4000,5000,10000,15000,20000,25000,30000,35000,40000,45000,50000,55000,60000,65000,70000]
MES_TRAIN_FLOOR: 202001
MES_TRAIN_CEILING: 202102
MES_TO_DROP: [202006]
MES_VALIDACION: 202103
MES_TEST: 202105
FINAL_TRAIN_FLOOR: 202004
FINAL_TRAIN_CEILING: 202105
FINAL_PREDICT: 202107
GANANCIA_ACIERTO: 780000
COSTO_ESTIMULO: 20000
RUN_BAYESIAN_OPTIMIZATION: True
UNDERSAMPLING_FRACTION: 0.1
IS_EXPERIMENTO : True
N_TRIALS : 0
